title: EmojiLingo
theme: minima
# markdown: kramdown
languages: ["en", "it"]
exclude_from_localizations: ["javascript", "images", "css"]
# default_locale_in_subfolder: true

baseurl: ""

plugins:
  - jekyll-multiple-languages-plugin