title: Emojilingo
theme: minima
# remote-theme: minima
markdown: kramdown
languages: ["en", "it"]
exclude_from_localizations: ["javascript", "images", "css"]
# default_locale_in_subfolder: true

baseurl: ""
destination: docs/

plugins:
  - jekyll-multiple-languages-plugin