- name: Notify the commit on Telegram Emojilingo Group
    uses: EverythingSuckz/github-telegram-notify@main
    with:
      bot_token: '${{ secrets.BOT_TOKEN }}'
      chat_id: '${{ secrets.CHAT_ID }}'
